[tools]
tflint = "latest"
pre-commit = "latest"
terraform = "1"

[tasks]
setup = ["pre-commit install", "tflint --init"]
lint = [
    "terraform fmt", 
    "tflint",
    "tflint --chdir modules --recursive"
]
precommit = ["pre-commit run --all-files"]

