#!/bin/bash
apt-get update
apt-get install -y jq unzip earlyoom postgresql-client
sudo hostnamectl set-hostname bastion

curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install

export AWS_REGION=${region}
export AWS_DEFAULT_REGION=${region}

# Get database credentials from Secrets Manager
DB_CREDS=$(aws secretsmanager get-secret-value --secret-id "${database_secret_arn}" --query SecretString --output text)
DB_USERNAME=$(echo "$DB_CREDS" | jq -r .username)
DB_PASSWORD=$(echo "$DB_CREDS" | jq -r .password)

CLICKHOUSE_PG_URL=""
if [ -n "${clickhouse_host}" ]; then
  CLICKHOUSE_PASSWORD=$(aws secretsmanager get-secret-value --secret-id "${clickhouse_secret_arn}" --query SecretString --output text | jq -r .password)
  CLICKHOUSE_PG_URL="http://default:$CLICKHOUSE_PASSWORD@${clickhouse_host}:8123/default"
fi

cat <<EOF > /etc/braintrust.env
export AWS_REGION=${region}
export AWS_DEFAULT_REGION=${region}
export REDIS_URL=redis://${redis_host}:${redis_port}
export PG_URL=postgres://$DB_USERNAME:$DB_PASSWORD@${database_host}/postgres
export CLICKHOUSE_PG_URL=${CLICKHOUSE_PG_URL}
EOF

echo -e "\nsource /etc/braintrust.env\n" >> /home/ubuntu/.bashrc

cat <<'EOF' > /home/ubuntu/list-instances.sh
#!/bin/bash
json=$(aws autoscaling describe-auto-scaling-groups --filters "Name=tag:BraintrustDeploymentName,Values=${deployment_name}")

if [ "$1" == "--json" ]; then
  echo "$json"
else
  echo "Brainstore Instances:"
  echo "$json" | jq -r '.AutoScalingGroups[] | select(.AutoScalingGroupName | contains("Brainstore")) | .Instances[] | .InstanceId'
  echo "Clickhouse Instances:"
  echo "$json" | jq -r '.AutoScalingGroups[] | select(.AutoScalingGroupName | contains("Clickhouse")) | .Instances[] | .InstanceId'
fi
EOF

cat <<EOF > /home/ubuntu/list-functions.sh
#!/bin/bash
# Unfortunately we can't support "aws lambda list-functions" because it shows environment variables
# with secrets for their entire account and not just the Braintrust stack. IAM won't let you restrict it.
# This output is generated by Cloudformation.
echo "${deployment_name}-migrate-database"
echo "${deployment_name}-api-handler"
echo "${deployment_name}-ai-proxy"
echo "${deployment_name}-initialize-primer"
EOF

# Randomly generated key used to jump to other Braintrust instances
mkdir -p /home/ubuntu/.ssh
chmod 700 /home/ubuntu/.ssh
ssh-keygen -t rsa -C "Braintrust Generated Bastion Key" -f /home/ubuntu/.ssh/id_rsa -N ""
chown ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa*

cat <<'EOF' > /home/ubuntu/ec2-connect.sh
#!/bin/bash

json=$(./list-instances.sh --json)
az=$(echo "$json" | jq -r ".AutoScalingGroups[].Instances[] | select(.InstanceId == \"$1\") | .AvailabilityZone")

os_user="ubuntu"
echo "Sending SSH key to instance $os_user@$1"
aws ec2-instance-connect send-ssh-public-key \
  --instance-id "$1" \
  --instance-os-user "$os_user" \
  --ssh-public-key file:///home/ubuntu/.ssh/id_rsa.pub \
  --availability-zone "$az"
echo "Connecting to instance $os_user@$1"
aws ec2-instance-connect ssh \
  --instance-id "$1" \
  --os-user "$os_user" \
  --private-key-file "$HOME/.ssh/id_rsa" \
  --connection-type direct
EOF

chmod +x /home/ubuntu/*.sh
chown ubuntu:ubuntu /home/ubuntu/*.sh
