apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.reader.nodePoolName }}
spec:
  template:
    metadata:
      labels:
        role: brainstore-reader
    spec:
      taints:
        - key: dedicated
          value: brainstore
          effect: NoSchedule
      requirements:
        - key: eks.amazonaws.com/instance-family
          operator: In
          values:
{{ toYaml .Values.instanceFamilies | indent 12 }}
        - key: eks.amazonaws.com/instance-size
          operator: In
          values:
{{ toYaml .Values.reader.instanceSizes | indent 12 }}
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - spot
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: {{ .Values.reader.nodeClassName }}
  limits:
    cpu: {{ .Values.reader.cpuLimit | quote }}
    memory: {{ .Values.reader.memoryLimit | quote }}
