apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: {{ .Values.writer.nodeClassName }}
spec:
  role: {{ .Values.nodeRoleName | quote }}
  ephemeralStorage:
    size: {{ .Values.writer.ephemeralStorageSize | quote }}
  subnetSelectorTerms:
    - tags:
        {{ .Values.subnetTagKey }}: {{ .Values.subnetTagValue | quote }}
  securityGroupSelectorTerms:
    - tags:
        {{ .Values.securityGroupKey }}: {{ .Values.securityGroupValue | quote }}
